### ISSUE TITLE
PUT/POST without Body on /cloud/project/{service_name}/ai/job/{job_id}/kill

### ISSUE THREAD

**Issue by bertrand-benoit** [ovh/python-ovh#104]
Issue is very similar to https://github.com/ovh/python-ovh/issues/95 with the /cloud/project/{service_name}/ai/job/{job_id}/kill entrypoint.

Unfortunately the trip to call directly `client.call('PUT', '/cloud/project/{serviceName}/user/{userID}/s3Credentials')` is not enough, because the OVH API returns 204 (good), and no content (good), but this OVH package attempts to convert this 'no content' to json, which is thus failing:
```
ovh/client.py", line 423, in call
    raise InvalidResponse("Failed to decode API response", error)
ovh.exceptions.InvalidResponse: ('Failed to decode API response', JSONDecodeError('Expecting value: line 1 column 1 (char 0)'))

```

**Comment by rbeuque74** [comment]
Hello,
Sorry for the delay,
This issue will be fixed in `v1.0.0`.
