### ISSUE TITLE
Use maintainable dependencies for testing

### ISSUE THREAD

**Issue by rominf** [ovh/python-ovh#111]
I'm Fedora maintainer and I'm in the process of packaging `python-ovh` for Fedora. Unfortunately, `python-ovh` relies on `yanc` (not in the repos, newest version released: Dec 16, 2014) and old `nose` (Fedora has newer, incompatible version), which makes it hard to test the library. Please consider updating testing dependencies (tox/pytest would be perfect).

**Comment by deathiop** [comment]
Hi @rominf,

Dependencies of python-ovh have recently been updated, especially to use pytest.
Can you give it another look and tell us if it suits you needs nowadays?

**Comment by rominf** [comment]
Hi @deathiop,

Yes, it works great! Thanks!
