### ISSUE TITLE
debian package for v1.1.0 ? or no longer provided?

### ISSUE THREAD

**Issue by flucas1** [ovh/python-ovh#125]
What is the policy about providing debian packages?
It is expected to have them in each release?

**Comment by simon-mueller** [comment]
+1

**Comment by deathiop** [comment]
Hi there,
The 1.1.0 release has been updated to include a Debian package.
Sorry for the time it took.

**Comment by simon-mueller** [comment]
Uploaded? Where to?

https://tracker.debian.org/pkg/python3-ovh

gives me a 404.

**Comment by deathiop** [comment]
It is attached to the GitHub release: https://github.com/ovh/python-ovh/releases/download/v1.1.0/python3-ovh_1.1.0_all.deb
