### ISSUE TITLE
Tag version naming scheme

### ISSUE THREAD

**Issue by rominf** [ovh/python-ovh#139]
Previously, tag version names started with a prefix "v": https://github.com/ovh/python-ovh/releases. However, the tag version name for the last release has no prefix "v": https://github.com/ovh/python-ovh/releases/tag/1.2.0. Was this change intentional? Will all subsequent releases also have no prefix?

Knowing the tag version naming scheme is necessary for maintaining the `python-ovh` package for Fedora using packit: https://src.fedoraproject.org/rpms/python-ovh/blob/rawhide/f/.packit.yaml.

Personally, I would keep the old "v" prefix, but if this change was intentional and all following releases will have no prefix, that is also acceptable.

**Comment by deathiop** [comment]
Hello @rominf,

This was not intentional: I made a mistake when releasing.
The tags are now consistent. Thanks for your feedback!
