### ISSUE TITLE
APIError('This call has not been granted')

### ISSUE THREAD

**Issue by Jetfire27** [ovh/python-ovh#141]
Hello,

I am trying to call your API POST /service/{serviceId}/renew from my Python project. I can retrieve all my services and check the renew API with GET, but when I attempt to use the POST method, I receive the following response:

403 APIError('This call has not been granted')

When I try from [here](https://eu.api.ovh.com/console/?section=%2Fservice&branch=v1#post-/service/-serviceId-/renew), everything works fine. However, when I use the requests library instead of your OVH library, I encounter an authentication error. If I add the bearer token from the linked page after I log in, my API call works fine also with the requests library.

**Comment by mxpetit** [comment]
Hello @Jetfire27 , can you share a query id on the failing request please?
You can get it by looking up the value inside the "x-ovh-queryid" response header

**Comment by Jetfire27** [comment]
Hi @mxpetit,
Of coursei can:

('x-ovh-queryid', 'EU.ext-5.67125487.614899.887b262fec1185338af5088b03ebeb14')

Thanks

**Comment by mxpetit** [comment]
From what I can see, the 403 response comes from a missing / non-matching `accessRules` linked to your credential.
You can verify that by requesting the route [/auth/currentCredential](https://eu.api.ovh.com/console/?section=%2Fauth&branch=v1#get-/auth/currentCredential) with the credential you previously used.
In order to fix your issue, you can do a [POST /auth/credential](https://eu.api.ovh.com/console/?section=%2Fauth&branch=v1#post-/auth/credential) with an `accessRule` granting `POST /service/{serviceId}/renew`.

**Comment by Jetfire27** [comment]
ok, i understand what you mean. Probably i miss some steps becouse when I try to call /auth/currentCredential i have the next response:

{
  "class": "Client::BadRequest",
  "message": "This call can only be used with API credentials"
}

What can i do for fix my issue? Thanks a lot

**Comment by mxpetit** [comment]
Can you double check that you did use the very same credentials as in your first request to POST /service/{serviceId}/renew?
The error message you gave states that `/auth/currentCredential` requires an API credential, which tells me that you used two different kind of authentication to perform 1) POST /service/{serviceId}/renew and 2) /auth/currentCredential.
2) must be performed with your usual application key (AK)

**Comment by Jetfire27** [comment]
when i initialize my class, i set the AK - AS - CK and then i just do call them.

```
class  OvhCtrl(HostingABC):
    def __init__(self):
        self.config = Config.objects.first()
        self.client = ovh.Client(
            endpoint='ovh-eu',
            application_key=self.config.application_key,
            application_secret=self.config.application_secret,
            consumer_key=self.config.consumer_key,
        )
```
        
Then inside a function
 ```
info = self.client.get(f'/service/{slave.service_id_bk}/renew')
info_selected = info if len(info) == 1 else [x for x in info if x['renewPeriod'] == 'P1Y']

try:
    params = {'dryRun': False, 'duration': info_selected[0]['renewPeriod'], 'services': [slave.service_id_bk]}
    response = self.client.post(f'/service/{slave.service_id_bk}/renew', **params)
    print(response)
except Exception as e:
    raise e
```

This line is where i meet my first issue (the one of the first post):
```
response = self.client.post(f'/service/{slave.service_id_bk}/renew', **params)
```


However i tryed [/auth/currentCredential](https://eu.api.ovh.com/console/?section=%2Fauth&branch=v1#get-/auth/currentCredential) from the page and give me 

{
"class": "Client::BadRequest",
"message": "Questa chiamata può essere utilizzata solo con credenziali API"
}

If i switch to another API for example /auth/details in the same page, will work fine.

Thanks for help and i hope you understand everything, english is not my first language

**Comment by Jetfire27** [comment]
Hi @mxpetit,
I have some news about my issue.

The latest version 1.2 of the ovh library, which I installed with the pip command, uses this endpoint:

```
# Mapping between OVH API region names and corresponding endpoints
ENDPOINTS = {
    "ovh-eu": "https://eu.api.ovh.com/1.0",
    "ovh-us": "https://api.us.ovhcloud.com/1.0",
    "ovh-ca": "https://ca.api.ovh.com/1.0",
    "kimsufi-eu": "https://eu.api.kimsufi.com/1.0",
    "kimsufi-ca": "https://ca.api.kimsufi.com/1.0",
    "soyoustart-eu": "https://eu.api.soyoustart.com/1.0",
    "soyoustart-ca": "https://ca.api.soyoustart.com/1.0",
}
```
The webpage that I use to test the API, which explicitly states that it is the stable production version, at [this link](https://eu.api.ovh.com/console/?section=%2FallDom&branch=v1) uses a different endpoint that starts with:

```
https://eu.api.ovh.com/v1
```

After speaking with the OVH assistant, I received this old console link to test the API [link here](https://eu.api.ovh.com/console-old/) that uses the same endpoint as the library.

With this new console, I can correctly use the GET /auth/currentCredential API, but not the one for renewing a service.

I think the API works correctly, but some endpoints use one URL format, and others use a different one. The problem is that the library can only use one of them.

A quick fix, until the stable API is truly stable, could be to add a parameter to the four client.[METHOD] functions, where it is possible to specify old_console=True (with the default set to False). This parameter would be passed to the call function and then to raw_call, where an if statement could manage the target variable accordingly.

**Comment by amstuta** [comment]
Hello @Jetfire27,

`https://eu.api.ovh.com/v1` and `https://eu.api.ovh.com/1.0` are just aliases and both point to the exact same API.

Your issue has nothing to do with the console that is used: the only difference between the two consoles is the authentication method, which explains that on the old one you are able to perform a call to `/auth/currentCredential`. If you want to call this route, you can either use the old console like you did, but the preferred way is to do it using directly the Python SDK.

Coming back to your original issue, you should check the `rules` field in the response body of `/auth/currentCredential`: your issue probably comes from the fact that your credential doesn't allow you access to `POST /service/{serviceId}/renew`.

**Comment by Jetfire27** [comment]
hi @amstuta and thanks for reply,
this is my auth/currentCredential response (section rules):

```
rules: [
-{
method: "GET"
path: "/*"
}
-{
method: "POST"
path: "/*"
}
-{
method: "PUT"
path: "/*"
}
-{
method: "DELETE"
path: "/*"
}
]
status: "validated"
```

**Comment by amstuta** [comment]
I think you got this response using the console at https://eu.api.ovh.com/console-old/ ? When you login on this console, it creates a new set of credentials, and if you don't change the values the default value is what you just sent.

Can you try this call from your Python script, using the same credentials as the ones you used when you got a 403 on `POST /service/{serviceId}/renew` ?

I just checked the access rules related to your application key `34d........3b7`, the only access granted is:
```
method: "GET",
path: "/*"
```

So no POST is allowed, this is the reason of your 403.

**Comment by Jetfire27** [comment]
Yes, i do it from old console.
I cannot find a way to change this permissions, did you have a link where i can do it?

**Comment by amstuta** [comment]
You must create a new set of credentials using this page: https://www.ovh.com/auth/api/createToken

Don't forget to update the `Validity` and `Rights` as the following:
![Screenshot 2024-10-22 at 11-42-03 Control panel - OVHcloud](https://github.com/user-attachments/assets/f6510f61-2a83-4b3b-b926-3a17d90d88b3)

**Comment by Jetfire27** [comment]
ok, thanks a lot, now is working
