### ISSUE TITLE
Low HTTP request failed error

### ISSUE THREAD

**Issue by dbadia** [ovh/python-ovh#23]
Hi, trying to execute one of the examples but am getting an error.
I've gotten my key, secret key, and consumer key.   Have endpoint=ovh-ca in my ovh.conf file along with the keys

Here's my code, config and the error I'm getting:
```python
# to get your credentials
client = ovh.Client()
# Print nice welcome message
print "Welcome", client.get('/me')['firstname']
```

Error
```console
INFO:ovh.vendor.requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): ca.api.ovh.com
Welcome
Traceback (most recent call last):
  File "hw.py", line 29, in <module>
    print "Welcome", client.get('/me')['firstname']
  File "/usr/local/lib/python2.7/dist-packages/ovh/client.py", line 319, in get
    return self.call('GET', _target, None, _need_auth)
  File "/usr/local/lib/python2.7/dist-packages/ovh/client.py", line 404, in call
    now = str(int(time.time()) + self.time_delta)
  File "/usr/local/lib/python2.7/dist-packages/ovh/client.py", line 197, in time_delta
    server_time = self.get('/auth/time', _need_auth=False)
  File "/usr/local/lib/python2.7/dist-packages/ovh/client.py", line 319, in get
    return self.call('GET', _target, None, _need_auth)
  File "/usr/local/lib/python2.7/dist-packages/ovh/client.py", line 422, in call
    raise HTTPError("Low HTTP request failed error", error)
ovh.exceptions.HTTPError: ('Low HTTP request failed error', SSLError(SSLError(IOError(2, 'No such file or directory'),),))
```

**Comment by yadutaf** [comment]
Hi @dbadia,

Thanks for reporting this issue. To help diagnose, can you give me your version of python-ovh (current is 0.4.1), operating system version, python version and paste the output of this snippet?

```python
import ovh
client = ovh.Client("ovh-ca")
print client.get("/auth/time",  _need_auth=False))
```

Thanks!

**Comment by vin173** [comment]
I get the same "Low http request failed" error with every api call that I try to run. So I tried your snippet and get the same http request error.
I'm running OS X El Capitan. ovh version 0.4.1 and python 2.7.10 in the latest version of virtualenv
[low http request error.txt](https://github.com/ovh/python-ovh/files/211874/low.http.request.error.txt)

**Comment by dbadia** [comment]
I typed this up on friday, but forgot to send it :)

I ran pip install ovh yesterday

Debian jessie

Python 2.7.9 (default, Mar  1 2015, 12:57:24)
[GCC 4.9.2] on linux2

Ran your snippit, here's what I got

dave@jj:~/ovhpy$ python test.py
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    print client.get("/auth/time",  _need_auth=False)
  File "/usr/local/lib/python2.7/dist-packages/ovh/client.py", line 319, in
get
    return self.call('GET', _target, None, _need_auth)
  File "/usr/local/lib/python2.7/dist-packages/ovh/client.py", line 422, in
cal
l
    raise HTTPError("Low HTTP request failed error", error)
ovh.exceptions.HTTPError: ('Low HTTP request failed error',
SSLError(SSLError(I
OError(2, 'No such file or directory'),),))
dave@jj:~/ovhpy$ python test.py
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    print client.get("/auth/time",  _need_auth=False)
  File "/usr/local/lib/python2.7/dist-packages/ovh/client.py", line 319, in
get
    return self.call('GET', _target, None, _need_auth)
  File "/usr/local/lib/python2.7/dist-packages/ovh/client.py", line 422, in
call
    raise HTTPError("Low HTTP request failed error", error)
ovh.exceptions.HTTPError: ('Low HTTP request failed error',
SSLError(SSLError(IOError(2, 'No such file or directory'),),))

**Comment by yadutaf** [comment]
Arghhhh. Python packaging....

This is caused by https://github.com/ovh/python-ovh/blob/master/ovh/vendor/requests/cacert.pem being missing in the package. I'll fix this ASAP.

In the mean time, you can manually grab it by running

```
wget https://raw.githubusercontent.com/ovh/python-ovh/master/ovh/vendor/requests/cacert.pem -O $(dirname $(python -c 'import ovh; print ovh.__file__'))/vendor/requests/cacert.pem
```

That should fix it for now.

**Comment by dbadia** [comment]
That worked, thanks!

**Comment by vin173** [comment]
Thank you for the quick fix

**Comment by yadutaf** [comment]
This is fixed. Version 0.4.2 released. Please run ``pip install -U ovh`` to get the latest version.

**Comment by asaphe** [comment]
Using version ovhapi-2.1 and I had this issue.
Using `wget https://raw.githubusercontent.com/ovh/python-ovh/master/ovh/vendor/requests/cacert.pem -O $(dirname $(python -c 'import ovh; print ovh.__file__'))/vendor/requests/cacert.pem` as noted by @yadutaf works.

FYI
