### ISSUE TITLE
ovh.exceptions.APIError: Service is temporarily unavailable 

### ISSUE THREAD

**Issue by JuliAcosta803** [ovh/python-ovh#47]
i have this code to add vps server item in my cart:
```
client.post('/order/cart/{cartid}/vps',
                  duration='PT18.179651S',
                  planCode='vps_ceph-nvme_model3',
                  pricingMode='default',
                  quantity=1)
```
But the answer gives me the following error:
ovh.exceptions.APIError: Service is temporarily unavailable 
OVH-Query-ID: CA.ws-2.592b81b1.10921.5307

**Comment by geoffreybauduin** [comment]
Hey,

this is probably because your duration looks wrong. If you want to order for 1 month, you should specify `duration="P1M"`. Duration parameter follows the ISO 8601.
