### ISSUE TITLE
Drop python 2.6 support

### ISSUE THREAD

**Issue by rbeuque74** [ovh/python-ovh#68]
Hello,
Following this last failing build on Python 2.6 (https://travis-ci.org/ovh/python-ovh/jobs/452406500) regarding SNI requirements on ca.api.soyoustart.com and ca.api.kimsufi.com, I recommand that we drop Python 2.6 support on python-ovh.

Python 2.6 is no longer supported by the Python core team, and pip will also drop support for Python 2.6 too, I think we should consider to move on.

Any objection ?

**Comment by VincentCasse** [comment]
I approve this change. Python 2.6 will die also if EU APIs are migrated on infra that handle SNI...

**Comment by hugovk** [comment]
Here's the pip installs for ovh from PyPI for last month:

| category | percent | downloads |
|----------|--------:|----------:|
|      3.5 |  39.91% |     2,803 |
|      2.7 |  29.54% |     2,075 |
|      3.6 |  24.36% |     1,711 |
|      3.7 |   2.99% |       210 |
| null     |   1.69% |       119 |
|      3.4 |   1.51% |       106 |
| Total    |         |     7,024 |


Source: `pypistats python_minor --last-month ovh`

You could also drop 3.2 and 3.3, which are also EOL and no longer receiving security updates (or any updates) from the core Python team.

Version | Release date | Supported until
--- | ---------- | ----------
2.5 | 2006-09-19 | 2011-05-26
2.6 | 2008-10-01 | 2013-10-29
3.0 | 2008-12-03 | 2009-06-27
3.1 | 2009-06-27 | 2012-04-09
3.2 | 2011-02-20 | 2016-02-27
3.3 | 2012-09-29 | 2017-09-29

Source: https://en.wikipedia.org/wiki/CPython#Version_history

**Comment by rbeuque74** [comment]
> You could also drop 3.2 and 3.3, which are also EOL and no longer receiving security updates (or any updates) from the core Python team.

Thanks for all the data provided. 
@geoffreybauduin any thoughts ?

**Comment by geoffreybauduin** [comment]
@rbeuque74 all good let's drop the support
