### ISSUE TITLE
how to call /me/bill with date range ?

### ISSUE THREAD

**Issue by nchauvat** [ovh/python-ovh#76]
Hi,

https://api.ovh.com/console/#/me/bill#GET says options are date.from date.to and orderId.

The example states:

result = client.get('/me/bill', 
    date.from='2019-01-01', // Filter the value of date property (>=) (type: datetime)
    date.to=None, // Filter the value of date property (<=) (type: datetime)
    orderId=None, // Filter the value of orderId property (=) (type: long)
)

how is this supposed to work in python since the keyword arguments cannot be named with a dot in the middle ?

I tried date, datefrom, _from, etc. but did not get it to work. Reading the source and the canonicalize method did not help me either.

I look forward to the correct syntax. Thank you.

**Comment by rbeuque74** [comment]
Hello,
I suggest you use:

```python
params = {'date.from': '2019-01-01', 'date.to': None, 'orderId': None}
result = client.get('/me/bill', **params)
```

The example generator on API Console is kind of broken for those kind of tricky part, we will have a look to fix it.
Thanks
Romain
