### ISSUE TITLE
Pb avec API /télephony et l'ajout d'un agent dans une queue

### ISSUE THREAD

**Issue by jraigneau** [ovh/python-ovh#87]
Hello,

I'm using OVH /telephony API to manage agents and queues but I've an issue with 

`POST /telephony/{billingAccount}/easyHunting/{serviceName}/hunting/queue/{queueId}/agent`

This request should create a new skill for an agent (it adds the agent in a queue) as stated in the docs (https://eu.api.ovh.com/console/#/telephony)

But no agent ID is posted in the request (nor is accepted), and I've got this error (using the api on eu.api.ovh.com/console/#/telephony or with my own code) (obviously I've got agents and agents ID to be put in the queue)

`Traceback (most recent call last):
  File "GetLineProperties.py", line 72, in <module>
    queue_add_agent(1668903,2)
  File "GetLineProperties.py", line 57, in queue_add_agent
    result = client.post('/telephony/'+billingAccount+'/easyHunting/'+serviceName+'/hunting/queue/'+queue+"/agent/",
  File "/home/superman/.local/lib/python3.8/site-packages/ovh/client.py", line 377, in post
    return self.call('POST', _target, kwargs, _need_auth)
  File "/home/superman/.local/lib/python3.8/site-packages/ovh/client.py", line 445, in call
    raise BadParametersError(json_result.get('message'),
ovh.exceptions.BadParametersError: Agent  doest not exist, create it first
OVH-Query-ID: EU.ext-2.5f22a3d7.28601.b25639bb-7876-4a01-997d-7d0b41cb63f9`

NB: the response class in the API docs mentions an "Agent ID"

`{
-telephony.OvhPabxHuntingAgentQueue: {
description: "Agent assigned to a queue"
-properties: {
-agentId: {
type: "long"
fullType: "long"
canBeNull: false
readOnly: true
required: false
}
-position: {
type: "long"
fullType: "long"
canBeNull: false
readOnly: false
description: "The position in the queue"
required: false
}
-queueId: {
type: "long"
fullType: "long"
canBeNull: false
readOnly: true
required: false
}
}
}
}`

Is there any issue with this request in the API (someone forgot an "AgentID" variable ?) ?

**Comment by bodji** [comment]
Hi,

You can use this call : 

POST /telephony/{billingAccount}/easyHunting/{serviceName}/hunting/agent/{agentId}/queue

It contains the agentId parameter.

**Comment by rbeuque74** [comment]
Hello,
Closing as stalled, and doesn't concerns `python-ovh`. Feel free to reopen if still relevant.

Romain
