### ISSUE TITLE
Pb with new api call PUT for nodepool

### ISSUE THREAD

**Issue by damien-lizeo** [ovh/python-ovh#88]
Hi,

The method PUT on the api /cloud/project/*/kube/*/nodepool/* has a 204 response instead of 200.
I know it's weird ... but I guess it's still in progress.

I guess a check for result emptyness is missing here
```
        # attempt to decode and return the response
        try:
            json_result = result.json()
        except ValueError as error:
            raise InvalidResponse("Failed to decode API response", error)
```

I can use the raw_call but it will be nice tu use put method.

log :
```
[DEBUG] "PUT /1.0/cloud/project/XXXXXXX/kube/XXXXXX/nodepool/XXXXXHTTP/1.1" 204 0
[ERROR] ('Failed to decode API response', JSONDecodeError('Expecting value: line 1 column 1 (char 0)'))
```

**Comment by rbeuque74** [comment]
Hello,
This issue refers the same problem than #91, I will handle this issue on #91.

Closing for duplicate.
Romain
