### ISSUE TITLE
ContentDecodingError POST /cloud/project/{service_name}/kube

### ISSUE THREAD

**Issue by treussart** [ovh/python-ovh#90]
Hi
I have an error when I want to create a new instance of K8s managed by OVH : 

`ovh.exceptions.HTTPError: ('Low HTTP request failed error', ContentDecodingError(DecodeError('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing data: incorrect header check'))))`

I am using Python 3.9 and python-ovh 0.5.0 :
```
lib/python3.9/site-packages/ovh/client.py", line 415, in call
    raise HTTPError("Low HTTP request failed error", error)
```
The endpoint API : POST /cloud/project/{service_name}/kube
Body : 
`{'name': 'Test', 'region': 'SBG5', 'version': '1.18', 'nodepool': {'antiAffinity': True, 'desiredNodes': 3, 'flavorName': 'b2-15', 'maxNodes': 10, 'minNodes': 3, 'monthlyBilled': False, 'name': 'node-pool-test-1'}}
`

**Comment by rbeuque74** [comment]
Hello,
This bug has been fixed in `v0.6.0`.
