### ISSUE TITLE
module 'ovh' has no attribute 'Client'

### ISSUE THREAD

**Issue by ibexnet** [ovh/python-ovh#94]
Hi everybody,
I have installed ovh module via pip and I have latest version:

xxx$ pip3 list | grep ovh
ovh          0.5.0

when I run the script I have the following error:
Traceback (most recent call last):
  File "/Users/xxx/Script/./ovh.py", line 5, in <module>
    import ovh
  File "/Users/xxx/Script/ovh.py", line 7, in <module>
    client = ovh.Client(
AttributeError: partially initialized module 'ovh' has no attribute 'Client' (most likely due to a circular import)

**Comment by squidly** [comment]
Hi, 

The problem is most likely that your script is named ovh.py ( like the module ).

Regards
